# Generated by Django 6.0.6 on 2026-06-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textannotation',
            name='alternatives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='textdataset',
            name='context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='textdataset',
            name='granularity',
            field=models.CharField(choices=[('sentence', 'Phrase'), ('word', 'Mot')], default='sentence', max_length=10),
        ),
    ]
